---
title: "BCF simulation"
output: pdf_document
latex_engine: xelatex
header-includes:
- \usepackage{blkarray}
- \usepackage{amsmath}
---







```{r}
# function to generate data
generate_data <- function(n=250, hetero=0, nonlinear=0) {
  x  <- matrix(rnorm(n*3), nrow = n)   
  dichotomous_var <- rbinom(n, size = 1, prob = 0.5)
  categorical_var <- sample(1:3, size = n, replace = TRUE)
  
  x <- cbind(x, dichotomous_var, categorical_var)
  colnames(x) <- c('x1','x2','x3','x4','x5')
  
  # treatment effect
  tau <- if (!hetero) {
    rep(3, n)
  } else {
    1 + 2 * x[,2] * x[,4]
  }
  
  # mu
  if (!nonlinear) {
    mu <- 1 + (2 * (x[,5] == 1) - 1 * (x[,5] == 2) - 4 * (x[,5] == 3)) + x[,1] * x[,3]
  } else {
    mu <-  -6 + (2 * (x[,5] == 1) - 1 * (x[,5] == 2) - 4 * (x[,5] == 3)) + 6 * abs(x[,3]-1) 
    
  }
  
  # propensity score
  s <- sd(mu)
  ui <- runif(n)                     
  pi <- 0.8 * pnorm( (3 * mu) / s - 0.5 * x[,1] ) + 0.05 + ui/10 
  
  # treatment
  Z <- rbinom(n, 1, pi)
  
  # outcome 
  Y <- mu + tau*Z + rnorm(n, 0, 1)  
  
  data.frame(x, tau, mu, pi, Z, Y)
}
```



```{r}
# function to calculate the ATE in each method
library(bcf)
library(BART)
library(lmerTest)

# BCF
tau_hat_bcf <- function(Y, Z, X, pihat) {
  colMeans(
    bcf(y = Y, z = Z,
        x_control = X,
        x_moderate = X,
        pihat = pihat,
        nburn = 1000, nsim = 1000,
        ntree_control = 200, ntree_moderate = 50)$tau
  )
}

# BART T-learner
tau_hat_tlearner <- function(Y, Z, X) {
  fit1 <- gbart(x.train = X[Z==1,], y.train = Y[Z==1],
                ntree = 100, ndpost = 1000)
  fit0 <- gbart(x.train = X[Z==0,], y.train = Y[Z==0],
                ntree = 100, ndpost = 1000)
  mu1 <- predict(fit1, X)
  mu0 <- predict(fit0, X)
  colMeans(mu1 - mu0)
}


# Simple linear regression  (ATE = coefficient of Z)
tau_hat_lm <- function(Y, Z, X) {
  dat <- data.frame(Y = Y, Z = Z, X)
  fit <- lm(Y ~ Z + ., data = dat)          
  betaZ <- coef(fit)["Z"]                   
  rep(betaZ, length(Y))                    
}


tau_hat_mlm <- function(Y, Z, X) {
  
  dat <- data.frame(Y = Y, Z = Z, X)
  dat$x5 <- factor(dat$x5)    
  
  # 
  fit <- lmer(
    Y ~ Z + x1 + x2 + x3 + x4 + (1 + Z+ x1 + x2 + x3 + x4 | x5),
    data = dat, REML = FALSE
  )
  
  
  beta_fix <- fixef(fit)["Z"]
  

  ranef_Z <- ranef(fit)[["x5"]][ ,"Z"]
  
  ##  CATE
  beta_group <- beta_fix + ranef_Z[ dat$x5 ]
  beta_group
}
```

```{r}
# simulation function
# calculate the bias of ATE in each simulation
one_rep <- function(rep_id, hetero = 0, nonlinear = 0) {
  # set.seed(6 * rep_id)   
  sim <- generate_data(n = 250,
                       hetero = hetero,        
                       nonlinear = nonlinear)
  X  <- as.matrix(sim[, c("x1","x2","x3","x4","x5")])
  Y  <- sim$Y
  Z  <- sim$Z
  true_ATE <- mean(sim$tau)
  
  # pihat for BCF
  p.score <- glm(Z ~ x1 + x2 + x3 + factor(x4) + factor(x5),
                data   = as.data.frame(X),
                 family = binomial(link = "probit"))
  
  pihat   <- predict(p.score, type = "response")

  c(BCF = mean(tau_hat_bcf(Y,Z,X,pihat)) - true_ATE,
    Tlearner = mean(tau_hat_tlearner(Y,Z,X)) - true_ATE,
    LM = mean(tau_hat_lm(Y,Z,X)) - true_ATE,
    MLM = mean(tau_hat_mlm(Y,Z,X)) - true_ATE)
  
}
```

```{r}
# simulations
library(future.apply)
plan(multisession, workers = 20)            
RPT <- 50

dgp_grid <- expand.grid(
  hetero    = c(0, 1),      # 0 = homogeneous, 1 = heterogeneous
  nonlinear = c(0, 1)       # 0 = linear,      1 = nonlinear 
)

dgp_grid$tag <- paste0(
  ifelse(dgp_grid$hetero == 0, "Homo", "Hetero"),
  "-",
  ifelse(dgp_grid$nonlinear == 0, "Linear", "Nonlinear")
)

for (k in seq_len(nrow(dgp_grid))) {
  
  H <- dgp_grid$hetero[k]
  N <- dgp_grid$nonlinear[k]
  label <- dgp_grid$tag[k]        
  
  # independent replications for each DGP
  bias_mat <- future_sapply(
    1:RPT,
    function(rep_id) one_rep(rep_id, hetero = H, nonlinear = N)
  )
  
 
  write.csv(bias_mat,
            file = paste0("result/bias_", label, ".csv"),
            row.names = TRUE)
}
```



```{r}
# plot the result
# calculate the RMSE and confidence interval for bias.

library(ggplot2)
library(tidyr)
library(purrr)
library(dplyr)

file_stub <- c("result/bias_Homo-Linear",
               "result/bias_Homo-Nonlinear",
               "result/bias_Hetero-Linear",
               "result/bias_Hetero-Nonlinear")

files_csv <- paste0(file_stub, ".csv")   

process_one <- function(fpath, scen_name) {
  mat <- as.matrix(read.csv(fpath, row.names = 1))
  as.data.frame(mat) %>%
    mutate(method = rownames(mat)) %>%
    pivot_longer(cols = -method,
                names_to = "rep",
                values_to = "bias"
      ) %>%
    mutate(scenario = scen_name)
}

df_bias <- map2_dfr(files_csv, file_stub, process_one)
df_bias <- df_bias %>%
  mutate(scenario = gsub("^result/bias_", "", scenario))

# boxplot for Bias
ggplot(df_bias, aes(x = method, y = bias, fill = method)) +
  geom_boxplot() +
  facet_wrap(~ scenario, ncol = 1) +
  labs(title = "ATE Bias comparison across  DGPs",
       x = NULL, y = "Bias (ÂTE − ATE_true)") +
  theme_minimal()



# check RMSE
df_rmse <- df_bias %>%
  group_by(scenario, method) %>%
  summarise(rmse = sqrt(mean(bias^2))) 
  

print(df_rmse)
```
